version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - DB_CONN_STRING=mongodb+srv://admin:admin123@solitapreassignment.ps5jtov.mongodb.net/?retryWrites=true&w=majority